steps:
  # Step 1: Checkout the code from the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/awang265/wangle-cloud-platform.git', 'source']  # Cloning into 'source' directory

  # Step 4: Copy files to Cloud Storage bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'source/website/*', 'gs://www.wanglecloudplatform.com']  # Upload contents of 'source' directory to the specified bucket
